# Generated by Django 3.0.4 on 2020-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
